name: Generate ASCII Artwork

on: push

jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay program
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run For cover, I'm a Dragon ... GRGR" >> dragon.txt

      - name: Sleep for 30 secs
        run: sleep 30

  test_job2:
    needs: build_job1 
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 secs
        run: sleep 10

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

  deploy_job3:
    needs: test_job2
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying..."
