name: Matrix Config

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
      strategy:
        matrix:
            os: [unutnut-latest, ubuntu-20.04 , windows-latest ]
            images: [hello-world, alpine]
      runs-on: ${{ matrix.os }}
      steps:
      - name: echo Docker Details
        run: docker info 

      - name: Run images on ${{ matrix.images }}
        run: docker run ${{ matrix.images }}

    # deploy_on_windows:
    #   runs-on: windows-latest
    #   steps:
    #   - name: echo Docker Details
    #     run: docker info 

    #   - name: Run images
    #     run: docker run hello-world