name: Matrix Config

on:
    push:
    workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false #GitHub will continue running all matrix jobs, even if one fails
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest]
        images: [hello-world, alpine]
        exclude: 
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-22.04

    runs-on: ${{ matrix.os }}
    steps:
      - name: Show Docker Info
        run: docker info

      - name: Run Docker Image on ${{ matrix.images }}
        run: docker run ${{ matrix.images }}


    # deploy_on_windows:
    #   runs-on: windows-latest
    #   steps:
    #   - name: echo Docker Details
    #     run: docker info 

    #   - name: Run images
    #     run: docker run hello-world