name: exploring vars and secrets

on:
    workflow_dispatch:
    # schedule:
    #   - cron: "*/1 * * * *"
    push: 


env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Docker login 
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker publish
        run: echo docker push $CONTAINER_REGISTRY/${{ env.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: docker
    concurrency:
        group: production-deployement
        cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker container
        timeout-minutes: 1
        run: |
            echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
            sleep 60s

     

# docker:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker build
    #       env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: bdockerfatnassi
    #         IMAGE_NAME: github-actions-nginx
    #       run: echo  docker build -t $[{ env.CONTAINER_REGISTRY }]/$DOCKER_USERNAME/$IMAGE_NAME:latest

    #     - name: Docker login
    #       env:
    #         DOCKER_PASSWORD: Dockerbaha2001**
    #         DOCKER_USERNAME: bdockerfatnassi
    #       run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    #     - name: Docker Publish 
    #       env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: bdockerfatnassi
    #         IMAGE_NAME: github-actions-nginx
    #       run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    # deploy:
    #     needs: docker
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker build
    #       env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: bdockerfatnassi
    #         IMAGE_NAME: github-actions-nginx
    #       run: echo  docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest