name: Exploring Workflow Filters and Activities

on:
  # ✅ Allows manual run from GitHub interface (green "Run workflow" button)
  workflow_dispatch:

  # ✅ Run workflow when pushing to the main branch
  # ❌ Ignore pushes to branches starting with "feature/"
  push:
    branches:
      - main                 # Only trigger on push to main
    branches-ignore:
      - feature/*            # Ignore any push to branches like feature/login, feature/test

  # ✅ Run workflow when a Pull Request is opened or closed
  # ❌ But ignore if only the README.md file was changed
  pull_request:
    types:
      - opened              # When PR is created
      - closed              # When PR is closed or merged
    paths-ignore:
      - README.md           # Don’t run if PR only touches README.md
    branches:
      - main                # Only if PR targets the main branch

jobs:
  hello:
    runs-on: ubuntu-latest   # Use Ubuntu environment
    steps:
      - run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}        
      # 👆 This prints what kind of event triggered the workflow (push, PR, etc.)
