name: Exploring Workflow Filters and Activities

on:
  # 🔘 Allows manual run from GitHub interface
  workflow_dispatch:

  # ⏰ Scheduled run (currently commented out)
  # schedule:
  #   - cron: "*/59 * * * *"  # Every 59 minutes

  # Trigger on push, except for the branches listed below
  push:
    branches: 
        - main                    # Ignore push on main branch
        - '!feature/*'           # ⚠️ Tries to ignore feature/* using '!', but this syntax is incorrect
    # branches-ignore:
    #   - feature/*              # Correct way to ignore branches starting with 'feature/'
    #   - test/**                # Correct way to ignore branches under 'test/'

  # 🔄 Trigger on pull request open or close on main branch, but ignore README.md changes
  pull_request: 
    types:
        - opened                 # Trigger when  Pull Request is opened
        - closed                 # Trigger when  Pull Request is closed
    paths-ignore:
        - README.md              # Ignore if only README.md is changed
    branches:
        - main                   # Only trigger if  Pull Request targets the main branch

jobs:
  hello:
    runs-on: ubuntu-latest       # Use Ubuntu runner
    steps:
      - run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}
        # 🖨️ Print which event (push, PR, etc.) triggered the workflow
