name: Exploring Workflow Filters and Activities

on:
  # ✅ Manual run from GitHub UI
  workflow_dispatch:

  # ✅ Trigger on push — except for feature branches
  push:
    branches-ignore:
      - feature/*             # Ignore any branch like feature/login, feature/test, etc.

  # ✅ Trigger on Pull Request events to main (open or close)
  # ❌ Ignore PRs that only touch README.md
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md
    branches:
      - main                 # Only PRs targeting main

jobs:
  hello:
    runs-on: ubuntu-latest   # Use Ubuntu runner
    steps:
      - name: Show event type
        run: |
          echo "This workflow was triggered by:"
          echo "${{ github.event_name }}"
